name: dsci-532_2026_32_Uber_dashboard
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - pip
  - pandas
  - matplotlib
  - seaborn
  - ipykernel

  - pip:
      - shiny==1.5.1
      - shinywidgets==0.7.1
      - plotly==6.5.2
      - pandas==3.0.1
      - python-dateutil==2.9.0.post0
      - uvicorn==0.41.0
      - kagglehub==1.0.0
