name: dsci-532_2026_32_Uber_dashboard
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - jupyterlab
  - notebook
  - ipykernel
  - scikit-learn
  - scipy
  - ridgeplot
  - openai
  - anthropic

  - pip:
      - shiny
      - shinywidgets
      - faicons
      - uvicorn
      - kagglehub
